source "https://github.com/CocoaPods/Old-Specs"

# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

# Uncomment this line if you're using Swift
use_frameworks!

target 'MogroChat' do

    pod 'Firebase'
    pod 'Firebase/Auth'
    pod 'GoogleSignIn'
    pod 'JSQMessagesViewController'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'SDWebImage'

end

